server:
  port: 8082


eureka:
  client:
    enabled: false

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true

spring:
  config:
    use-legacy-processing: true
    import: ConfigServer:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
    stream:
      bindings:
        input:
          destination: reservation-topic
          content-type: application/json
  data:
    mongodb:
      host: localhost
      port: 27017
      database: guestrepo
  zipkin:
    enabled: false