server:
  port: 8085


#eureka:
#  client:
#    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotelrepo
  zipkin:
    enabled: false