server:
  port: 8086


eureka:
  client:
    enabled: false

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: reservation-topic
          content-type: application/json
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reservationsagarepo
  zipkin:
    enabled: false
